package at.qe.g1t2.model;

import jakarta.persistence.*;
import org.hibernate.envers.Audited;
import org.springframework.data.domain.Persistable;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * This class represents a Picture entity in a system that seems to involve environmental plant monitoring. Its id is being
 * autogenerated. Additionally, this entity contains attributes such as pictureName and description which are responsible for
 * describing the picture. On the other hand, the path attribute is connecting each picture to its own sensorStation.
 */

@Entity
@Audited
public class Picture implements Persistable<String>, Serializable, Comparable<Picture> {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;
    private String pictureName;
    private String description;
    @Column(nullable = false)
    private String path;
    @Column(nullable = false)
    private LocalDateTime createDate;

    @ManyToOne(optional = false)
    private SensorStation sensorStation;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Picture picture = (Picture) o;
        return Objects.equals(id, picture.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public int compareTo(Picture o) {
        return String.valueOf(o.id).compareTo(id);
    }

    @Override
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public boolean isNew() {
        return null == createDate;
    }

    public String getPictureName() {
        return pictureName;
    }

    public void setPictureName(String pictureName) {
        this.pictureName = pictureName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public SensorStation getSensorStation() {
        return sensorStation;
    }

    public void setSensorStation(SensorStation sensorStation) {
        this.sensorStation = sensorStation;
    }
}
